### ISSUE TITLE
Applied Energistics cable

### ISSUE THREAD

**Issue by gamecraft45** [KaiKikuchi/ForgeRestrictor#13]
When player clicking fast (or clicking fast on cable than block around and after back on cable and still repeat) with wrench cable sometimes break

![2016-03-25_17 05 52](https://cloud.githubusercontent.com/assets/7279856/14048137/99737754-f2ac-11e5-8269-555fdbb00c35.png)

**Comment by KaiKikuchi** [comment]
I'm sorry but this can't be fixed because of Bukkit/Forge issues with events. You can find who does that on the server log.
