### ISSUE TITLE
[Suggestion] Blacklist

### ISSUE THREAD

**Issue by spannerman79** [KaiKikuchi/ForgeRestrictor#14]
You have a whitelist option - what about a outright blacklisting option.  Anything on that list is forbidden so to speak - exact opposite to a whitelist

**Comment by KaiKikuchi** [comment]
I'm sorry but I don't think I'll ever add this:
- Usually you want to protect as much as you can so you can avoid griefing
- Sometimes it's not easy to detect what item is causing some damage

Also this plugin is already unable to blocking some item. Such option would allow more items to escape from this plugin protection.
