### ISSUE TITLE
Event Expression in console  

### ISSUE THREAD

**Issue by MJRLegends** [KaiKikuchi/ForgeRestrictor#17]
Here is the error taken from the log http://pastebin.com/Fq8WSSqW..

Edit: Just thought i'd add that im using the latest version..

**Comment by KaiKikuchi** [comment]
Sorry I missed this issue. MC1.7.10?

**Comment by MJRLegends** [comment]
Yeah

**Comment by MJRLegends** [comment]
Seems to be related to DAMAGE_ANIMALS

**Comment by KaiKikuchi** [comment]
Yeah I see that. What's your WorldGuard version?

**Comment by MJRLegends** [comment]
worldguard-6.0.0-beta-05

**Comment by KaiKikuchi** [comment]
This is really weird. I am using WorldGuard 6 API, and it has that flag. But your beta version seems to not have that flag. We use WG6.1 in our servers and it works fine. Maybe you should update too?

**Comment by MJRLegends** [comment]
i will give it a test tomorrow

**Comment by MJRLegends** [comment]
i cant say i've seen this message in chat so must be fixed....
