### ISSUE TITLE
Spam on mob hit

### ISSUE THREAD

**Issue by Esctogrillo** [KaiKikuchi/ForgeRestrictor#20]
I'm getting this message every time I hit a mob:

http://pastebin.com/juMFqR3n

Using Thermos 58 (forge + bukkit)
GriefPreventionPlus 12.28
Forge Restrictor  1.4 DEV 10

**Comment by KaiKikuchi** [comment]
This is an issue with WorldGuard. It has been already reported here: https://github.com/KaiKikuchi/ForgeRestrictor/issues/17
