### ISSUE TITLE
GravityGun

### ISSUE THREAD

**Issue by checkium** [KaiKikuchi/ForgeRestrictor#22]
What "mode" should I use to protect claims against GravityGun? For portal gun I think its range but didn't test yet, correct me if I'm wrong.

**Comment by KaiKikuchi** [comment]
Honestly I don't know. I suggest to check GravityGun's config and see if you can tweak it.

**Comment by checkium** [comment]
There's nothing in it's config, also, I looked into his code, and for gravity gun it uses an entity

**Comment by Eufranio** [comment]
ForgeRestrictor is an bukkit plugin and probably will not be able to track the modded entities's actions.
