### ISSUE TITLE
Enhance ranged protection

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/ForgeRestrictor#23]
As the plugin says, **Ranged: items in this list are ranged items. Like a bow. They can shoot far away, all items in this list will check the target block.**. However, the check made will be only when the item is first right-clicked, meaning that when the player stop pressing the right button, nothing will happen. My suggestion is to enhance that protection a bit, checking if the player **still** holding the item when moving. Look at an example:

As the info says, it would protect from things like a bow. You can easily right-click using the bow looking for a un-protected area, move the cursor to a protected area, and then release the button. 

You could add a check when moving the cursor. If the player, on move, is looking for a protected area + holding/using the item, run your logic. The actual way won't protect even against a bow, as it is supposed to.

**Comment by KaiKikuchi** [comment]
Unfortunately this is not possible within the Bukkit API. Do you think I missed something like that?

You can use the AoE protection instead.
