### ISSUE TITLE
plugin blocking the click

### ISSUE THREAD

**Issue by EduardoMGP** [KaiKikuchi/ForgeRestrictor#29]
hello, I know there is already an answer to my problem
But she was not a solution for me.

the ForgeRestrictor plugin blocks clicks on the sign
making it impossible to sell items in the chestshop plugin
the purchase of items works normally
only when selling item the plugin does not allow and confiscate items
there is a way to sell that is just breaking the plate
but this would be time consuming and bad
even with /containertrust is the click on the terrain is prohibited
How to fix this?
thank you

Version: 1.7.10

```
ForgeRestrictor v1.4-DEV-13
ChestShop v3.7.17
WorldGuard v6,1
GriefPreventionPlus v13.3
```

**Comment by spannerman79** [comment]
Use [QuickShop](https://github.com/KaiKikuchi/QuickShop)

**Comment by EduardoMGP** [comment]
The problem is that it's not just with the board
the protection of the world guard also occurs this


When killing a mob he confiscates inventory items
even with flags connected
mob dies and washes damage plus no sword damage
and by the hand
the sword can kill the mob with 1 hit more as the plugin confiscates it the mob dies just giving several hit...

http://prntscr.com/h7k3fk
