### ISSUE TITLE
Additional mod support

### ISSUE THREAD

**Issue by LuxusDarkangel** [KaiKikuchi/ForgeRestrictor#4]
Right now Fres prevents players from using items in a claim where they don't have permissions, but they can still use his hand. This mean they still can grief things like JABBA's barrels or TE's Cache. I don't know if it is possible to protect them because of how they work, but it's worth the try.

**Comment by KaiKikuchi** [comment]
Woops... I accidentally removed that protection.

**Comment by KaiKikuchi** [comment]
Hello. This should be fixed in v.1.3.3. Thank you for reporting this!
