### ISSUE TITLE
doesnt seem to be working in 1.7.10

### ISSUE THREAD

**Issue by djoveryde** [KaiKikuchi/ForgeRestrictor#5]
Hi, i've recently added it to my Tekkit Legends Server however for some reason its not showing up in the /plugins list. The command doesnt seem to work either.
Any ideas?

**Comment by KaiKikuchi** [comment]
Post your server log. Please use pastebin.com or similar.

**Comment by djoveryde** [comment]
http://pastebin.com/Jk8hKypD

**Comment by KaiKikuchi** [comment]
> Caused by: java.lang.UnsupportedClassVersionError
You need java 1.8
