### ISSUE TITLE
EventException error

### ISSUE THREAD

**Issue by djoveryde** [KaiKikuchi/ForgeRestrictor#8]
I've just installed ForgeRestrictor v1.4 onto my server. Im using 6.1 Worldguard but am receiving the following error spamming console.

Any ideas?

http://pastebin.com/XrrMxGta

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your report! I updated the DEV build, you can download the latest build here:
https://github.com/KaiKikuchi/ForgeRestrictor/releases/tag/v1.4-DEV-3

If the error persists, please reopen this issue.

**Comment by djoveryde** [comment]
That seems to have fixed it. It also fixed an issue that was found out just before I updated in which players couldnt kill any mobs/animals in the wilderness.

**Comment by KaiKikuchi** [comment]
Thank you for your feedback. Notice that you're using a development build so you may find a lot of bugs.

**Comment by djoveryde** [comment]
Yes, its fine, i will report any issues I encounter. Also regarding the wild issue i've made another issue regarding it as it actually isnt fixed, im just removing the plugin temporarily to confirm its definately that.

**Comment by KaiKikuchi** [comment]
You may want to try the latest stable release:
https://github.com/KaiKikuchi/ForgeRestrictor/releases/tag/v1.3.4
