### ISSUE TITLE
Console Spam, default config.

### ISSUE THREAD

**Issue by djoveryde** [KaiKikuchi/ForgeRestrictor#9]
The latest version seems to spam console with:

01.02 16:13:28 [Server] INFO Confiscated Tito_Mekani items for 3 ticks
01.02 16:13:27 [Server] INFO Confiscated Tito_Mekani items for 3 ticks
01.02 16:13:27 [Server] INFO Confiscated Tito_Mekani items for 3 ticks
01.02 16:13:26 [Server] INFO Confiscated Tito_Mekani items for 3 ticks

Not sure if thats meant to happen. The config file is set to default so nothing has been added.

**Comment by KaiKikuchi** [comment]
That's spammed when someone tries to use a modded item inside a protected region and they don't have permission there. You should test without op/region permissions.

**Comment by djoveryde** [comment]
The message seems to be occuring when the player is at their Faction Base?

**Comment by KaiKikuchi** [comment]
Do the players have build permission?

**Comment by djoveryde** [comment]
They do yes.

**Comment by djoveryde** [comment]
Its almost like its behaving as though it needs to see the block in order to authorise what the player is about to do if that makes sense?

**Comment by KaiKikuchi** [comment]
If there isn't a target block, it'll just check player's location.
https://github.com/KaiKikuchi/ForgeRestrictor/blob/master/src/main/java/net/kaikk/mc/fr/EventListener.java#L91

**Comment by djoveryde** [comment]
Weird, literally it occurs out in the open. Removing the plugin instantly fixes the issue. No console error either which doesnt help

**Comment by KaiKikuchi** [comment]
Ok can you provide more info about your server like cauldron version, worldguard version, faction version, any other plugin that can be involved with this...

Also, does this happen on the wilderness too?

**Comment by djoveryde** [comment]
yes wilderness included.
Version is KCauldron-1.7.10-1614.175.13-TCPR-UNOFFICIAL (https://github.com/TCPR/KCauldron/releases)
Factions 2.7.2
Worldguard 6.1

**Comment by KaiKikuchi** [comment]
Have you tested the latest stable release? 
https://github.com/KaiKikuchi/ForgeRestrictor/releases/tag/v1.3.4

**Comment by djoveryde** [comment]
Confirmed still occurs in 1.3.4. 
If a player tries to open their personal bags (Bag of Holding, backpack, Lexica Botania) it then spams console with the above message.

**Comment by leelawd** [comment]
I can confirm this issue only occurs in Build 13 of the Unofficial KCauldron. I am assuming it is because of https://github.com/TCPR/KCauldron/commit/9582467ea0ddf80fb7110d5eb6c865ec57c5560c

It acts as if 1 person has claimed the entire world but only when you right click an item in the air.

**Comment by KaiKikuchi** [comment]
@leelawd thank you for your report!

I was going to suggest you to use the latest **official** build of kCauldron you can find here:
https://repo.prok.pw/pw/prok/KCauldron/
